---
title: "Vollmer et al. Model"
output: html_notebook
---

```{r setup}
library(magrittr)
library(tidyverse)
library(cowplot)
library(ggridges)
library(haven)
library(latex2exp)
library(rstan)

source(file.path("..", "util.R"))

ggplot2::theme_set(theme_minimal())
```

# Prior Prediction

```{r}
ita_prior_results <- read_rds(file.path("data", "mobility", "results", "ita_mob_prior_results.rds"))
```

```{r}
ita_prior_results %>% 
  select(sb_region, param_results) %>% 
  unnest(param_results) %>% 
  filter(fct_match(parameter, "imputed_cases")) %>% 
  select(sub_region, iter_data) %>% 
  unnest(iter_data) %>% 
  ggplot(aes(iter_value)) +
  geom_density(aes(group = sub_region), color = alpha("black", 0.25)) +
  geom_vline(xintercept = 3.28, linetype = "dotted") +
  labs(title = TeX("Prior predicted $R_0$"), x = "") +
  NULL,
```


```{r, fig.width=10}
plot_grid(
  ita_prior_results %>% 
    select(sub_region, param_results) %>% 
    unnest(param_results) %>% 
    filter(fct_match(parameter, "R0")) %>% 
    select(sub_region, iter_data) %>% 
    unnest(iter_data) %>% 
    ggplot(aes(iter_value)) +
    geom_density(aes(group = sub_region), color = alpha("black", 0.25)) +
    geom_vline(xintercept = 3.28, linetype = "dotted") +
    labs(title = TeX("Prior predicted $R_0$"), x = "") +
    NULL,
  
  ita_prior_results %>% 
    select(sub_region, param_results) %>% 
    unnest(param_results) %>% 
    filter(fct_match(parameter, "subnational_effect_R0")) %>% 
    select(sub_region, iter_data) %>% 
    unnest(iter_data) %>% 
    ggplot(aes(iter_value * 3.28)) +
    geom_density() +
    geom_vline(xintercept = 3.28, linetype = "dotted") +
    ggrepel::geom_text_repel(aes(x, y, label = label), nudge_x = 1, data = tibble(x = 3.28, y = 1, label = "3.28")) +
    scale_x_continuous("", breaks = seq(1, 5, 1)) +
    labs(title = TeX("Prior predicted subnational effect on $R_0$")) +
    NULL,
  
  ncol = 2
)
```


```{r, fig.width=10}
ita_prior_results %>% 
    select(sub_region, daily_data) %>% 
    unnest(daily_data) %>% 
    select(sub_region, date, day_index, param_results) %>% 
    unnest(param_results) %>% {
      # plot_grid(
        filter(., fct_match(parameter, "mobility_effect")) %>%
          unnest(iter_data) %>%
          ggplot(aes(iter_value)) +
          geom_density(aes(group = sub_region), color = alpha("black", 0.3)) +
          labs(title = "Prior predicted mobility effect.", x = "")

        # filter(., fct_match(parameter, "Rt_adj")) %>% 
        #   unnest(iter_data) %>% 
        #   ggplot() +
        #   geom_density_ridges(aes(x = iter_value, y = factor(day_index))) +
        #   labs(title = TeX("Prior predicted adjusted $R_t$."), x = ""),
        
      #   ncol = 2
      # )
    }
```

# Analysis

## Italy

```{r}
ita_results <- read_rds(file.path("data", "mobility", "results", "ita_mob_results.rds"))
```

```{r it-R0-plot, fig.width=10}
ita_results %>% 
  plot_subnat_ci() + 
  coord_cartesian(xlim = c(1, 4.5)) +
  labs(title = TeX("R_{0,m}"))
```

```{r it-Rt-plot, fig.height=6, fig.width=10}
ita_results %>% 
  plot_day_ci() +
  geom_hline(yintercept = 1, linetype = "dotted") +
  labs(title = TeX("R_{t,m}")) 
```

```{r it-last-Rt-plot, fig.height=4, fig.width=10}
ita_results %>% 
  plot_last_day_ci() +
  geom_vline(xintercept = 1, linetype = "dotted") +
  labs(title = TeX("$R_{t,m}$ on the last day")) 
```

```{r, fig.height=10}
ita_results %>% 
  select(sub_region, daily_data) %>% 
  unnest(daily_data) %>% 
  select(sub_region, day_index, date, new_deaths, param_results) %>% {
    bind_rows(rep = unnest(., param_results) %>% 
                filter(fct_match(parameter, "deaths_rep")) %>% 
                select(sub_region, day_index, date, iter_data) %>% 
                unnest(iter_data) %>% 
                rename(new_deaths = iter_value),
              obs = select(., -param_results) %>% 
                mutate(iter_id = 0),
              .id = "est_type")
  } %>% 
  filter(iter_id %in% c(0, sample(max(iter_id), 5, replace = FALSE))) %>% 
  ggplot() +
  geom_col(aes(day_index, new_deaths, fill = est_type)) +
  labs(x = "", y = "") +
  scale_fill_discrete("", labels = c(obs = "Observed", rep = "Predicted")) +
  facet_grid(rows = vars(sub_region), cols = vars(iter_id), scales = "free_y", switch = "y") + 
  theme(
    legend.position = "top",
    strip.placement = "outside",
    axis.text.y = element_blank(),
    strip.text.x = element_blank(),
    strip.text.y = element_text(size = 7))
```
```{r, fig.width=14}
ita_results %>% 
  select(sub_region, daily_data) %>% 
  unnest(daily_data) %>% 
  select(sub_region, day_index, date, new_deaths, param_results) %>% {
    bind_rows(rep = unnest(., param_results) %>% 
                filter(fct_match(parameter, "deaths_rep")) %>% 
                select(sub_region, day_index, date, iter_data) %>% 
                unnest(iter_data) %>% 
                rename(new_deaths = iter_value) %>% 
                group_by(sub_region, iter_id) %>% 
                mutate(cumul_deaths = cumsum(new_deaths)) %>% 
                ungroup(),
              obs = select(., -param_results) %>% 
                group_by(sub_region) %>% 
                mutate(
                  cumul_deaths = cumsum(new_deaths),
                  iter_id = 0
                ) %>% 
                ungroup(),
              .id = "est_type")
  } %>% 
  filter(iter_id %in% c(0, sample(max(iter_id), 5, replace = FALSE))) %>% 
  ggplot() +
  # geom_col(aes(day_index, new_deaths, fill = est_type)) +
  # geom_col(aes(day_index, cumul_deaths, fill = est_type)) +
  geom_ribbon(aes(day_index, ymax = cumul_deaths, ymin = 0, fill = est_type), alpha = 0.5) +
  scale_fill_discrete("", labels = c(obs = "Observed", rep = "Predicted")) +
  labs(x = "", y = "") +
  facet_grid(rows = vars(sub_region), cols = vars(iter_id), scales = "free_y", switch = "y") + 
  theme(
    legend.position = "top",
    strip.placement = "outside",
    axis.text.y = element_blank(),
    strip.text.x = element_blank(),
    strip.text.y = element_text(size = 7))
```


## USA 

```{r}
usa_results <- read_rds(file.path("data", "mobility", "results", "usa_mob_results.rds"))
```

```{r us-R0-plot, fig.width=12}
usa_results %>% 
  plot_subnat_ci() + 
  coord_cartesian(xlim = c(1, 5.5)) +
  labs(title = TeX("R_{0,m}"))
```

```{r us-Rt-plot, fig.height=14, fig.width=16}
usa_results %>% 
  plot_day_ci() +
  geom_hline(yintercept = 1, linetype = "dotted") +
  labs(title = TeX("R_{t,m}")) 
```

```{r us-last-Rt-plot, fig.height=10, fig.width=10}
usa_results%>% 
  plot_last_day_ci() +
  geom_vline(xintercept = 1, linetype = "dotted") +
  labs(title = TeX("$R_{t,m}$ on the last day")) 
```

```{r, fig.width=14}
usa_results %>% 
  filter(fct_match(sub_region, c("New York", "Pennsylvania", "Texas", "Maryland", "Washington", "Florida"))) %>% 
  select(sub_region, daily_data) %>% 
  unnest(daily_data) %>% 
  select(sub_region, day_index, date, new_deaths, param_results) %>% {
    bind_rows(rep = unnest(., param_results) %>% 
                filter(fct_match(parameter, "deaths_rep")) %>% 
                select(sub_region, day_index, date, iter_data) %>% 
                unnest(iter_data) %>% 
                rename(new_deaths = iter_value) %>% 
                group_by(sub_region, iter_id) %>% 
                mutate(cumul_deaths = cumsum(new_deaths)) %>% 
                ungroup(),
              obs = select(., -param_results) %>% 
                group_by(sub_region) %>% 
                mutate(
                  cumul_deaths = cumsum(new_deaths),
                  iter_id = 0
                ) %>% 
                ungroup(),
              .id = "est_type")
  } %>% 
  filter(iter_id %in% c(0, sample(max(iter_id), 5, replace = FALSE))) %>% 
  ggplot() +
  # geom_col(aes(day_index, new_deaths, fill = est_type)) +
  # geom_col(aes(day_index, cumul_deaths, fill = est_type)) +
  geom_ribbon(aes(day_index, ymax = cumul_deaths, ymin = 0, fill = est_type), alpha = 0.5) +
  scale_fill_discrete("", labels = c(obs = "Observed", rep = "Predicted")) +
  labs(x = "", y = "") +
  facet_grid(rows = vars(sub_region), cols = vars(iter_id), scales = "free_y", switch = "y") + 
  theme(
    legend.position = "top",
    strip.placement = "outside",
    axis.text.y = element_blank(),
    strip.text.x = element_blank(),
    strip.text.y = element_text(size = 7))
```

```{r, fig.width=14}
usa_results %>% 
  filter(fct_match(sub_region, c("New York", "Pennsylvania", "Texas", "Maryland", "Washington", "Florida"))) %>% 
  select(sub_region, daily_data) %>% 
  unnest(daily_data) %>% 
  select(sub_region, day_index, date, new_deaths, param_results) %>% 
  unnest(param_results) %>% 
  filter(fct_match(parameter, "deaths_rep")) %>% 
  ggplot() +
  # geom_linerange(aes(x = day_index, ymin = per_0.1, ymax = per_0.9)) +
  geom_ribbon(aes(x = day_index, ymin = per_0.1, ymax = per_0.9), alpha = 0.5) +
  geom_point(aes(x = day_index, y = new_deaths)) +
  scale_y_continuous(breaks = seq(0, 5000, 200)) +
  # scale_fill_discrete("", labels = c(obs = "Observed", rep = "Predicted")) +
  # labs(x = "", y = "") +
  facet_wrap(vars(sub_region), scales = "free_y") + 
  # theme(
  #   legend.position = "top",
  #   strip.placement = "outside",
  #   axis.text.y = element_blank(),
  #   strip.text.x = element_blank(),
  #   strip.text.y = element_text(size = 7))
  NULL
```

```{r, fig.width=14}
usa_results %>% 
  filter(fct_match(sub_region, c("New York", "Pennsylvania", "Texas", "Maryland", "Washington", "Florida"))) %>% 
  select(sub_region, daily_data) %>% 
  unnest(daily_data) %>% 
  select(sub_region, day_index, date, new_deaths, param_results) %>% 
  unnest(param_results) %>% 
  filter(fct_match(parameter, "deaths_rep")) %>% 
  ggplot() +
  geom_ribbon(aes(x = day_index, ymin = per_0.1, ymax = per_0.9), alpha = 0.5) +
  geom_line(aes(x = day_index, y = new_deaths)) +
  scale_y_continuous(breaks = seq(0, 5000, 200)) +
  # scale_fill_discrete("", labels = c(obs = "Observed", rep = "Predicted")) +
  # labs(x = "", y = "") +
  facet_wrap(vars(sub_region), scales = "free_y") + 
  # theme(
  #   legend.position = "top",
  #   strip.placement = "outside",
  #   axis.text.y = element_blank(),
  #   strip.text.x = element_blank(),
  #   strip.text.y = element_text(size = 7))
  NULL
```

# Italy and USA

```{r}
ita_usa_results <- read_rds(file.path("data", "mobility", "results", "ita_usa_mob_results.rds"))
```

```{r us-R0-plot, fig.width=12, fig.height=15}
ita_usa_results %>% 
  plot_subnat_ci() + 
  coord_cartesian(xlim = c(1, 5.5)) +
  geom_vline(xintercept = 3.28, linetype = "dotted") +
  labs(title = TeX("R_{0,m}"))
```
