---
title: "Results for all countries"
date: "Last updated: `r Sys.Date()`"
output: pdf_document
---

```{r setup, include = FALSE}
library(magrittr)
library(tidyverse)
library(ggridges)
library(haven)
library(rstan)

source(file.path("..", "util.R"))

knitr::opts_chunk$set(fig.width=14, fig.height = 10, echo = FALSE)

ggplot2::theme_set(theme_minimal())

results <- readRDS("../data/mobility/results/lite_merged.rds")
```


# Mortality data

Japan and Malaysia will be fixed.

```{r mortality, fig.width=10, fig.height = 8}
results %>% 
  select(country_name, sub_region, daily_data, population) %>% 
  unnest(daily_data) %>%
  group_by(country_name, date) %>%
  summarise(deaths = sum(cum_deaths),
            deaths_per_mln = 1e06*sum(cum_deaths)/sum(population),
            .groups = "keep") %>%
  filter(deaths > 10) %>%
  ggplot(aes(x=date, y=deaths_per_mln, color = country_name)) + geom_line() + 
  scale_y_log10() +
  ggtitle("Cumulative COVID deaths per million inhabitants",
          "The model uses regional data (not shown).")
```


# Mobility data

United Kingdom will be fixed.

```{r mobility, fig.width=10, fig.height = 8}
results %>% 
  select(country_name, sub_region, daily_data, population) %>% 
  unnest(daily_data) %>%
  group_by(country_name, date) %>%
  summarise(mob = mean(g_transit_stations + g_workplaces + g_retail_and_recreation)) %>%
  ggplot(aes(x=date, y=mob, color = country_name)) + geom_line()+
  labs(y = "Avg mobility metric (naive mean over regions)") +
  ggtitle("Averaged mobility metrics per country",
          "The model uses regional data (not shown).")
```


# R0 and imputed cases

```{r params}
results %>% 
  unnest(param_results) %>%
  filter(parameter %in% c("R0", "imputed_cases")) %>%
  mutate(mean = ifelse(parameter == "imputed_cases", log(mean), mean)) %>%
  mutate(parameter = ifelse(parameter == "imputed_cases", "Log(seeded cases)", "R0")) %>% 
  ggplot(aes(y = country_name, x = mean, color = country_name)) + 
  geom_jitter() +
  theme(legend.position = "none") +
  facet_wrap( ~ parameter, ncol = 3, scales = "free") +
  ggtitle("Seeding and R0 for countries and regions",
        paste("Each point is a mean Bayesian estimate for a single region.\n", 
              "'Seeded cases' are the estimated number of infections 30 days prior to 10th death.\n",
              "Regions with low infection rates not included currently."))
```

# Beta coefficients with regions

Please ignore this output for now.

```{r betas}
results %>% 
  unnest(beta_results) %>%
  ggplot(aes(y = country_name, x = mean, color = country_name)) + 
  geom_jitter() +
  theme(legend.position = "none") +
  facet_wrap( ~ coef_index, ncol = 3, scales = "free")
```
