---
title: "Modeling Heterogeneous COVID-19 Spread"
output: pdf_document
header-includes:
  - \usepackage{pxfonts} 
bibliography: ../references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Research question

In what follows, we propose a Bayesian model that incorporates a number of different mechanisms that can explain heterogeneous epidemic growth rates. We then attempt to fit the model to national and sub-national data. We do this to, one, characterise heterogeneity in COVID spread and, two, to distinguish between the different factors that drive this heterogeneity. To do this, we use a hierarchical Bayesian model to synthesise evidence from the largest possible number of countries and regions.

We consider five main potential mechanisms that can explain why some regions have been affected less, with particular focus on the factors that may be operating in the developing countries: 1) low risk of severe outcomes, 2) low seeding, 3) low $\mathcal{R}_0$, 4) under-reporting of outcomes, 5) decrease in R over time due to behaviour change, government intervention or other factors.

_Low risk of severe disease_. While health care quality and utilisation may have an impact on COVID mortality, age is the main determinant of COVID outcomes. In developing countries mortality rates and risk of severe infections will therefore be lower. 

_Low seeding_. In deterministic models of infectious diseases, a single case is enough to start the exponential growth in infections. In the real world, however, due to stochastic nature of contacts, more cases may be needed to start an epidemic. We can assume that many places were not (yet) affected by the epidemic due to number of COVID cases at any point has not reached this epidemic threshold. This, in turn, can be due to low connectedness of different regions (especially in developing countries), early government restrictions on travel or simply due to chance.

_Low $\mathcal{R}_0$_. When reproductive rate of the virus is low, the numbers of cases may either decrease or build up very slowly, with no evident exponential trend for many months. Various factors can explain low $\mathcal{R}_0$

* Lower number of super-spreaders or super-spreading events
* Low population density 
* Social norms and social network structure
* Climate (fixed) or weather (time-dependent factors, which will act on $R_t$ - see below)

_Under-reporting or other data issues_. In many developing countries deaths due to COVID may either not be attributed to SARS-COV-2 infection or not recorded at all. Even worse, this under-counting cannot be assumed to be constant over time.

_Decrease over time_. Assuming that the virus was seeded in a particular setting and $\mathcal{R}_0$ is sufficiently high (as evidenced by some local outbreaks), the lack of subsequent epidemic could be explained by a few competing hypotheses: 

* Various government interventions designed to slow the spread of the virus through restrictions in activity, detection of cases, tracing of contacts
* Heterogeneous spread of the virus across communities. The higher risk, "higher R" individuals were affected first and the remaining part of the population reproduces the virus at lower rates. Herd immunity can also play a part in this mechanism. This is different from low $\mathcal{R}_0$, in that the initial observed infection rate will be high, and only subsequently decrease.
* Change in behaviour in the absence or in addition to government policy, such as can be observed in drops in mobility data in many countries which precede gov't intervention

We hope to distinguish between the five main mechanisms by using the Bayesian hierarchical model. However, many of the possible mechanisms that can lead to no epidemic are not distinguishable from each other. A simple example is the near reciprocal relationship of $R_0$ and initial seeding. 
For this reason, instead of following a hypothesis-testing approach, we will aim to make a probablistic argument and use subjective priors. For example, both $R_0$ and the number of cases early in the epidemic can have strongly informative prior distributions constructed based on travel data, literature on SARS transmission, models of seeding and history of contagion from previous pandemics _etc._ By introducing these additional assumptions we hope to be able to identify the main parameters of the model and characterise the main drivers of heterogeneity in the COVID impact.


# Data

We use data from 120 countries, 30 of which report COVID outcomes at a sub-national level (usually administrative regions such as states in the USA, lands in Germany, states in India etc.). We arrange our data in a hierarchical model, but if sub-national data are missing, we only estimate the national-level parameters (see below). When the sub0national estimates are available, the aggregate, national-level data are not used for inference. 

The inputs for each unit of analysis are: mobility data over time, mortality over time, population size, time to recording the first case, time to first $n$ deaths. (To be expanded.)
For each country we calculate the expected infection fatality rate (IFR) by reweighting the age-specific IFR estimated by @verity_estimates_2020 in Chinese individuals through age distribution based on World Population Prospects data.



# Bayesian model of COVID transmission in countries and regions

We extend @Vollmer2020 for our Bayesian modeling framework. The data generating process models the number of infections as latent outcomes, which then predicts the expected number of deaths, which then leads to observed, COVID-attributable deaths. Latent variables are linked through convolutions of random variables. The primary component of the model adds structure to how transmission of infection evolves over time predicted by observed outcomes. Vollmer et al. use Google mobility data as a measure of social contact, which we also do.

<!-- Karim and Witold - feel free to expand on the model here -->

First, the transmission of infection $c_{tm}$, in sub-region $m$ on day $t$, is modeled, for $t > 6$, as
\begin{align*} 
  c_{tm} &= S_{tm} R_{tm} \sum_{\tau=1}^{t-1} c_{\tau,m} \tilde{g}_{\tau - 1},  
\end{align*}
and for the first six days we impute the number of cases as
\begin{align*}
  c_{tm} = c_{m}^\textrm{imputed} &\sim \mathtt{Exponential}(\frac{1}{\tau^\textrm{imputed}}) \\ 
  \tau^{imputed} &\sim \mathtt{Exponential}(0.03)
\end{align*}

* $S_{tm} = 1 - \frac{\sum_{i = 1}^{t-1} c_{im}}{N_m}$ is the susceptible proportion of the population, where $N_m$ is the size of the population in sub-region $m$. 
* $\tilde{g}_s$ are a discretization of the a continuous generation \[ g \sim \mathtt{Gamma}(6.5, 0.62), \] such that $g_s = \int_{\min(s-0.5,0)}^{s+0.5} p_g(\tau)\ \mathrm{d}\tau$, where $p_g$ is the density function for $g$.

$R_{tm}$, the dynamic transmission rate is defined as 
\[ R_{tm} = R_{0,m} \cdot \left[ 2 \cdot \phi^{-1} (\mathbf{X}_{tm}\boldsymbol{\beta}_{m})\right] \cdot \rho_{tm}. \]
$R_{0m}$ is modeled as

\begin{align*} 
  \log R_{0m} &= \log R_0 + \delta_{k[m]} + \delta_m \\
  \log R_0 &\sim \mathtt{Normal}(\mu_{R_0}, \tau_{R_0}) \\
  \delta_{k} &\sim \mathtt{Normal}(0, \tau^{\delta,\textrm{nat}}) \\ 
  \delta_{m} &\sim \mathtt{Normal}(0, \tau^{\delta,\textrm{subnat}}_{k[m]}) \\
  \tau^{\delta,\textrm{nat}} &\sim \mathtt{Normal}^+(0, 0.1) \\
  \tau^{\delta,\textrm{subnat}}_k &\sim \mathtt{Normal}^+(0, 0.8).
\end{align*}
We use the subscript $k$ for countries and $m$ for their sub-regions. We use the following hyperparameters: $\tau_{R_0} = \sqrt{\log(\frac{0.25^2}{3.28^2} + 1)}, \mu_{R_0} = \log(3.28) - \frac{\tau_{R_0}^2}{2}$.^[Currently, we are only running countries separately so we are not using the national level effects on $R_0$.]   

$R_t$ is predicted in the inverse logit function by the variables in the design matrix $\mathbf{X}$ such that each parameter in the vector $\boldsymbol{\beta}_m$ is modeled as
\begin{align*}
  \beta_{pm} &= \beta_p + \gamma_{p,k[m]} + \gamma_{pm} \\
  \beta_p &\sim \mathtt{Normal}(0, 0.5) \\
  \gamma_{pk} &\sim \mathtt{Normal}(0, \tau^{\gamma,\textrm{nat}}) \\
  \gamma_{pm} &\sim \mathtt{Normal}(0, \tau^{\gamma,\textrm{subnat}}_{k[m]}) \\
  \tau^{\gamma,\textrm{nat}} &\sim \mathtt{Normal}^+(0, 0.25) \\
  \tau^{\gamma,\textrm{subnat}}_{k[m]} &\sim \mathtt{Normal}^+(0, 0.5).
\end{align*}
In addition, we include parametric model of reduced contact rate such that 
\begin{align*}
  \rho_{tm} &= \lambda_m + \frac{1 - \lambda_m}{1 + \exp(\kappa(t - t^*_m))} \\
  \lambda_m &\sim \mathtt{Beta}(3, 1) \\
  \kappa &\sim \mathtt{Normal}^-(0, 1). 
\end{align*}
This is a smoothly decreasing trend in contact representing unobservable qualitative changes in social contact not captured by mobility data. The midpoint of this trend, $t^*_m$, is the day the first covid-19 case is detected. __Work in progress, t* will be defined differently__

The expected number of deaths, $d_{tm}$ is modeled as
\begin{align*}
  d_{tm} = \textrm{ifr}^*_m \sum_{\tau = 1}^{t-1} c_{\tau,m} \tilde{\pi}_{t-\tau},
\end{align*}
where the infection fatality rate (IFR), $\textrm{ifr}^*_m$, is modeled as
\begin{align*}
  \textrm{ifr}^*_m &= \eta_m \cdot \textrm{ifr}_m \\
  \eta_m &\sim \mathtt{Normal}(1, 0.1).
\end{align*}
In other words we perturb the pre-calculated IFR by a small random variable. Time-to-deaths, $\pi_s$, is modeled as a continuous distribution
\[ \pi_s \sim \mathtt{Gamma}(5.1, 0.86) + \mathtt{Gamma}(17.8, 0.45),\]
which we discretized as $\tilde{\pi}_s = \int_{\min(s-0.5, 0)}^{s+0.5} p_\pi(\tau)\,\mathrm{d}\tau$, where $p_\pi$ is the density function of $\pi$.

Finally, the likelihood model for number of deaths, $D_{tm}$, is 
\[ D_{tm} \sim \mathtt{NegativeBinomial}(d_{tm}, d_{tm} + \frac{d_{tm}^2}{\psi}), \]
and $\psi \sim \mathtt{Normal}^+(0, 5)$.



# Preliminary Results

# References {-}
